name: build-arm

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [arm]
        goarm: [5, 6, 7]
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      continue-on-error: true
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        pre_command: |
          apt-get update && apt-get install -y musl-tools && export CGO_ENABLED=1 && export CC=musl-gcc
        ldflags: '-s -w -extldflags "-static"'
        extra_files: README.md .env.example
        asset_name: server-monitor-agent-go-${{ matrix.goos }}-${{ matrix.goarch }}-${{ matrix.goarm }}
